- name: Start a playbook
  hosts: all
  become: no
  tasks:

  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts

  - name: Print hostname
    ansible.builtin.debug:
      var: ansible_facts['nodename'] 

  - name: Print date
    ansible.builtin.debug:
      var: ansible_facts['date_time']['date']

  - name: Print IP
    ansible.builtin.debug:
      var: ansible_facts['enp1s0']['ipv4']['address']
  